project:
  type: website

# Website specific configuration
website:
  # The main title of your website, shown in the navbar.
  title: "Claudia Collarin"

  # Navigation bar settings
  navbar:
    # Icons and links on the right side of the navbar
    right:
      - icon: envelope # This is the new email icon
        href: "mailto:claudia.collarin@unive.it" # This creates the email link
      - icon: github
        href: https://github.com/ccollarin
      #- about.qmd
    # Links on the left side of the navbar
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      #- href: teaching.qmd
      #  text: Didattica

  # Footer settings
  page-footer:
    center: "© 2025 Claudia Collarin. Built with Quarto."
    right:
      - icon: envelope
        href: "mailto:claudia.collarin@unive.it"
      - icon: github
        href: https://github.com/your-username

format:
  html:
    theme: minty    # puoi cambiare tema: cosmo, lumen, flatly, ecc.
    css: styles.css # file opzionale di personalizzazione
    page-layout: full

